### ISSUE TITLE
Video Stabilizer outputs a few pixels from the top left corner of the input

### ISSUE THREAD

**Issue by unfa** [Crowsinc/LiveVisionKit#10]
**System/Software Setup**
 - **LiveVisionKit Version:** 1.2.0
 - **OBS Studio Version:** 27.2.4
 - **OS:** *Windows 10
 - **GPU:** Radeon RX6800XT, official Windows AMD driver
 - **CPU:** Ryzen 9 3900X

**Issue Description**

When adding video stabilizereffect the preview shows what looks like  pixels taken from the top left corner of the camera input. I  I wave my hand in that corner, the image color changes accordingly, that's how I've determined this is what's going on.

![image](https://user-images.githubusercontent.com/491704/181008636-714dd096-2eb3-4630-896d-88c8293f296a.png)

This also produces solid black (invisible) output in the scene view in OBS.

**Expected Behavior**
I'd expect to see the full camera frame stabilised.

**Reproduction Steps**
1. Install the add-on as instructed copying files to `C:\Program Files\obs-studio\`
2. Add a LVS Video Stabilizer effect onto a camera input.
3. Observe erronous image

**Comment by Crowsinc** [comment]
Hi, could you please provide me with a link to your OBS log and let me know whether the (LVK) Adaptive DeBlocker effect filter, with test mode turned on, also produces solid black output in the scene view or has any similar effects? More information about your camera and how it is set up (resolution, fps etc.) would be helpful too!

**Comment by unfa** [comment]
Hey!

The deblocker filter works fine, same with FSR sharpening.
The camera input is 1280x720p 60 FPS through a UVC HDMI -> USB converter.

I'd need to test again on Windows - my main work environment is Linux, so that's really where I focus my attention.

**Comment by soares1990** [comment]
Também estou com o mesmo problema.

**Comment by Crowsinc** [comment]
I have a good idea of what the issue is but I haven't found the cause yet because I have been unable to reproduce the bug. Access to an OBS log would greatly help confirm my diagnosis. 

Regardless, I will push some updates in LVK 1.2.1 which should hopefully stop this from happening.

**Comment by soares1990** [comment]
Ok. Obrigado pelo retorno. Fico no aguardo. Tem algo que consigo ir fazendo por aqui para testes?

**Comment by Crowsinc** [comment]
LiveVisionKit should be constantly printing out an error to the OBS log while this bug is happening, do you think you could let me know what it says?

Information about your OBS set up would also be helpful, such as how you are running the filter.

**Comment by D1aN1** [comment]
heres my logs. gives me black screen when using stabilizer.
[2022-09-24 18-56-32.txt](https://github.com/Crowsinc/LiveVisionKit/files/9639715/2022-09-24.18-56-32.txt)

**Comment by Crowsinc** [comment]
Hi, thanks for the log. I believe this issue comes from a bug in how OBS 27.0.0 copies textures. Updating to 27.1.0 or newer should fix the problem. Let me know how it goes!

**Comment by unfa** [comment]
On Arch Linux it seems to not be an issue running in OBS 28. Didn't check on Windows yet.

**Comment by Crowsinc** [comment]
Enough has changed under the hood in the last update, that its worth creating a fresh issue if his bug still exists for some users.
