### ISSUE TITLE
Compiling opencv with cuda/cudnn?

### ISSUE THREAD

**Issue by Corben78** [Crowsinc/LiveVisionKit#13]
**System/Software Setup**
 - **LiveVisionKit Version:** 1.2.0
 - **OBS Studio Version:** 27.2.4
 - **OS:** Ubuntu 20.04.5 LTS
 - **GPU:** nVidia 3070 515.76
 - **CPU:** intel i9-9900K

Is it beneficial to LiveVisionKit to compile opencv with cuda/cudnn support?

I'm able to compile opencv with opencl on Ubuntu 20.04.5 LTS (haven't updated to latest 22.04 yet), but I'm struggling getting cuda support compiled in. Now I'm wondering if it's worth putting in the effort to get cuda/cudnn support into opencv?

**Comment by Crowsinc** [comment]
Hi, LiveVisionKit doesn't use any of the cuda functions in OpenCV, so compiling with OpenCL support will be enough.
