### ISSUE TITLE
Video stabilizer stops working in OBS 29.1.0

### ISSUE THREAD

**Issue by ghost** [Crowsinc/LiveVisionKit#18]
**System/Software Setup**
 - **LiveVisionKit Version:** 1.2.2
 - **OBS Studio Version:** 29.1.0
 - **OS:** *Windows 10
 - **GPU:** GTX 1080Ti
 - **CPU:** Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz

**OBS Log:**: [...]

**Issue Description**
*Video Stabilizer*:
The video stabilizer filter won't "zoom in" any more so the green area of the stabilization is still visible in OBS/ the source.
This can be seen when toggling Test Mode on/ off. Turning Test off won't zoom the video in.
It's most likely the newest OBS version? It was working fine before the OBS update.
Re-installing LiveVisionKit also didn't fix it.

**Expected Behavior**
When Test Mode is unchecked the image should crop accordingly and zoom in.

**Reproduction Steps**
Updating to OBS version 29.1.0 breaks the LVK Video Stabilizer plugin. That's probably all there is to it.

**Supporting Evidence**
The issue can be seen in the following video:
https://www.youtube.com/watch?v=OAeooSB_hdk

**Appendix**
*Write anything useful which is not directly related to one of the questions above*

I hope this is getting fixed soon. C:
Thank you!

**Comment by Crowsinc** [comment]
Hi, thanks for the high quality report. Updating to OBS 29.1.0 does not reproduce the issue on my systems, so there is more to it unfortunately. 

Would you be able to share what the effect filter you have in the provided video is? An OBS log would also be useful if you are able to provide one!

Thanks.

**Comment by ghost** [comment]
Hi,

I have switched to my backup instance of OBS. Even though it says OBS 29.1.0 as well it is working fine. I might have made a mistake while copy-pasting the "old" files. I'm not too sure about it.

The effect filter is to blur the image. I am using the one from StreamFX.

BR
TwisterDX

**Comment by Crowsinc** [comment]
I will close the issue assuming it was just a copy mistake, regardless this type of problem is no longer possible in the upcoming update.
