### ISSUE TITLE
LoadLibrary failed for '../../obs-plugins/64bit/LiveVisionKit.dll': (null) (126)

### ISSUE THREAD

**Issue by maxboehm** [Crowsinc/LiveVisionKit#19]
**System/Software Setup**
 - **LiveVisionKit Version:** *The version of LiveVisionKit in use.*
 - **OBS Studio Version:** *The version of OBS Studio in use.*
 - **OS:** *Windows 10, Windows 11, or the specific Linux distribution.*
 - **GPU:** *The graphics card and graphics driver version in use.*
 - **CPU:** *The processor in use.*

**OBS Log:**: *A link to the OBS log corresponding with the issue. This can be done through OBS by going to - Help -> Log Files -> Upload Current Log File*

**Issue Description**
*Provide a clear and concise description of the issue.*

**Expected Behavior**
*Provide a clear and concise description of what should happen instead.*

**Reproduction Steps**
*Provide clear, numbered, instructions on how to reproduce the issue. If the reproduction steps look like "I opened OBS and it didn't work", then please provide more information about your OBS setup instead.*

**Supporting Evidence**
*If the issue is related to filter performance in a specific scene/scenario, you should provide a YouTube or Twitch link to a video which displays the issue, both with test mode on and off if the filter supports it.*

**Appendix**
*Write anything useful which is not directly related to one of the questions above*

**Comment by Crowsinc** [comment]
Resolved in Issue #20
