### ISSUE TITLE
Adapt Install Guide for Microsoft Visual C++ Redistributable

### ISSUE THREAD

**Issue by maxboehm** [Crowsinc/LiveVisionKit#20]
**What is the requested feature?**
In the install guide, an information is missing. In order for OBS to be able to load the LiveVisionKit.dll, the Microsoft Visual C++ Redistributable is necessary: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

Before installing the library, I've got the following error:
```
18:22:00.337: LoadLibrary failed for '../../obs-plugins/64bit/LiveVisionKit.dll': (null) (126)
18:22:00.337: Module '../../obs-plugins/64bit/LiveVisionKit.dll' not loaded
```

DependencyTreeWalker proved my guess :)

**Why do you want this feature?**
Others will have the same problem and might not be able to use this plugin.

**Comment by Crowsinc** [comment]
Thanks, I will add this as a note in the installation guide.
