### ISSUE TITLE
OBS Crashing

### ISSUE THREAD

**Issue by LonleyViper** [Crowsinc/LiveVisionKit#23]
Seems to occur when I use move source and take a screenshot.

Dedicated Streaming RIG:

 - **LiveVisionKit Version:** 1.2.2
 - **OBS Studio Version:** 29.1.3
 - **OS:** Windows 10
 - **GPU:** RTX 2060 SUPER - 536.23
 - **CPU:** i7 6700k

**OBS Log:**: 
[2023-07-10 18-26-59.txt](https://github.com/Crowsinc/LiveVisionKit/files/12013468/2023-07-10.18-26-59.txt)
[Crash 2023-07-10 23-05-37.txt](https://github.com/Crowsinc/LiveVisionKit/files/12013470/Crash.2023-07-10.23-05-37.txt)

**Issue Description**
OBS hard crashes,

**Expected Behavior**
OBS shouldnt hard crash. Crash happens at end of this stream: 

**Reproduction Steps**
Trigger OBS movesource to zoom in on area of primary display.
Take a screenshot.
Happens after 1hr to 1hr30mins

**Supporting Evidence**
(https://www.twitch.tv/videos/1868514631)

**Appendix**
*Write anything useful which is not directly related to one of the questions above*

**Comment by LonleyViper** [comment]
[2023-07-11 11-08-17.txt](https://github.com/Crowsinc/LiveVisionKit/files/12014231/2023-07-11.11-08-17.txt)

Replicated again. 51mins after stream start.

**Comment by Crowsinc** [comment]
Most likely the same or similar to issue #16 . Not much that can be done until someone is able to replicate it in a development environment, which I haven't been able to do yet.

**Comment by LonleyViper** [comment]
> Most likely the same or similar to issue #16 . Not much that can be done until someone is able to replicate it in a development environment, which I haven't been able to do yet.

Thanks!

**Comment by donmortis** [comment]
I used the upscaler, deblocker, and sharpening tools both together and separately. OBS works fine as long as I'm not streaming, but it freezes during streaming. I'm attaching the crash report.
[Crash 2023-10-30 15-21-54.txt](https://github.com/Crowsinc/LiveVisionKit/files/13209257/Crash.2023-10-30.15-21-54.txt)
[2023-10-30 15-29-11.txt](https://github.com/Crowsinc/LiveVisionKit/files/13209269/2023-10-30.15-29-11.txt)

**Comment by Crowsinc** [comment]
Ive moved your comment over into a new [issue](https://github.com/Crowsinc/LiveVisionKit/issues/28). I'm closing this issue as the original problem has already been discussed in existing tickets. 

@donmortis does the crash happen as a result of you doing something, or does it seem random?
