### ISSUE TITLE
Question about: The OpenCL interop context failed to pass validation tests and has been disabled!

### ISSUE THREAD

**Issue by ogmkp** [Crowsinc/LiveVisionKit#26]
**System/Software Setup**
 - **LiveVisionKit Version:** *1.2.1 (because only OpenCV 4.6.0 in Debian repo)*
 - **OBS Studio Version:** *29.1.3*
 - **OS:** *Debian 12*
 - **GPU:** *Nvidia GTX 970, driver version: 525.125.06 (from Debian repo)*
 - **CPU:** *Intel(R) Pentium(R) CPU G4560*

**OBS Log:**: 
*Initializing...
Version: 1.2.1
OpenCL Support: Yes
OpenCL Interop Support: Yes
FSR Effect Loaded: Yes
CAS Effect Loaded: Yes

The OpenCL interop context failed to pass validation tests and has been disabled!*

**Issue Description**
*The OBS log mention this:
The OpenCL interop context failed to pass validation tests and has been disabled!

**Expected Behavior**
*Don't know what this line bring or miss on functionnalities or bugs*

**Appendix**
*Can this line be problematic?*

Thank you for this great project!

**Comment by Crowsinc** [comment]
This is nothing to worry about. Using the OpenCL interop context can make LVK run 1-2ms faster, but there is no driver support for it on Linux past OBS-Studio 27 so it will fail for everyone.

**Comment by ogmkp** [comment]
Thanks for your reply.
It is possible to make LVK 1.2.2 or next with OpenCV 4.6.0 ?

**Comment by Crowsinc** [comment]
I'm planning on compiling OpenCV directly into LVK for future releases so that you don't need to source or compile the right OpenCV version yourself.

**Comment by ogmkp** [comment]
Great ! Can't wait for the release. Thanks for this !
