### ISSUE TITLE
More Fine Tuning in Crop for the Video Stabilizer

### ISSUE THREAD

**Issue by goamberg** [Crowsinc/LiveVisionKit#29]
**What is the requested feature?**
Some smaller adjustments for finetuning the stabilization.

- More flexible crop. eg. If using a 4:3 picture in a 16:9 frame you could use much more vertical space at top and bottom than left to right.

**Why do you want this feature?**
For an upcoming prototype on a helmet cam in skiing I want to try and finetune it more.

**Possible Use Cases**
I hope that it can be used in a live broadcast and streamed directly into the TV-Truck when presenting a prototype helmet cam and give additional stabilization.

**Examples**
This would be an example of the race where I would like to test it:
https://www.youtube.com/watch?v=SUZCzGrYke8
(video is only 30fps, normally its 50 or 60)

**Comment by Crowsinc** [comment]
Hi i've added independent width and height crop sliders and allowed decimal values to be used when choosing a crop. This will come out with the next update.
