### ISSUE TITLE
Crash and need for browser source.

### ISSUE THREAD

**Issue by lewkmiller** [Crowsinc/LiveVisionKit#6]
**System/Software Setup**
 - **LiveVisionKit Version - 1.1.0
 - **OBS Studio Version 27.2.4 (64bit)
 - **OS:** *Windows 10
 - **GPU: AMD Radeon PRO W6600
 - **CPU AMD Ryzen 7 5800X 8-Core Processor                3.80 GHz

**Issue Description**
I am attempting to apply the video stabilization filter to my webcam for testing. I apply and OBS crashes. Also I am unable to apply the video stabilization to a browser source. I want to use browser source because I am using VDO.Ninja for importing cameras. 
**Expected Behavior**
I just want the filter to work correctly and or at all.

**Reproduction Steps**
I opened OBS and added the video stabilization filter to a video source (webcam) and OBS throws an error message and it crashes. I will paste in the crash file contents.

LVK@C:\Users\sdm\Projects\C++\LiveVisionKit\LiveVisionKit\OBS\Interop\VisionFilter.cpp@VisionFilter(..) FAILED m_Context != nullptr && s_Filters.count(filter) == 0

**Comment by Crowsinc** [comment]
Hi, support for running the stabilizer on a browser source is expected to come in the next feature update. Please see [Issue #3](https://github.com/Crowsinc/LiveVisionKit/issues/3) for more information.

The error you are running into is rather strange and I'm unable to reproduce the bug on my end.  I will need some further information to help isolate the issue on your system:

**What source are you using to display your webcam on OBS?**

**Does the video stabilizer work on a media source such as the 'VLC Video Source'?**

**Does the '(LVK) Adaptive DeBlocker' filter work on either your webcam source or the 'VLC Video Source'?**

I don't expect LiveVisionKit 1.1.1 to fix the issue, but the error message has been split into two which should help narrow things down as well.
